version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /Users/girishbhatta/Documents/personal_repos/aqi-watcher/data:/home/postgres/pgdata/data


